import jsPDF from 'jspdf';

export default class ProfessionalPDFService {
  static generateComprehensivePDF(requirements: any[], questionnaire: any, fileName: string) {
    this.createBasicPDF('Comprehensive Report', requirements, questionnaire, fileName);
  }

  static generateQuestionnairePDF(questionnaire: any, fileName: string) {
    this.createBasicPDF('Questionnaire', [], questionnaire, fileName);
  }

  static generateAnalysisPDF(requirements: any[], fileName: string) {
    this.createBasicPDF('Analysis Report', requirements, null, fileName);
  }

  static generateGoldStandardPDF(requirements: any[], fileName: string) {
    this.createBasicPDF('Gold Standard', requirements, null, fileName);
  }

  private static createBasicPDF(
    type: string,
    requirements: any[],
    questionnaire: any,
    fileName: string
  ) {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.width;
    
    // Add header
    doc.setFillColor(30, 64, 175);
    doc.rect(0, 0, pageWidth, 40, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(20);
    doc.text(`GDC ${type.toUpperCase()}`, pageWidth / 2, 25, { align: 'center' });
    
    // Add content
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(12);
    doc.text(`Document: ${fileName}`, 20, 60);
    doc.text(`Generated: ${new Date().toLocaleDateString()}`, 20, 70);
    
    if (requirements.length > 0) {
      doc.text(`Requirements Analyzed: ${requirements.length}`, 20, 80);
      const overallScore = Math.round(requirements.reduce((sum: number, req: any) => sum + req.score, 0) / requirements.length);
      doc.text(`Overall Compliance: ${overallScore}%`, 20, 90);
    }
    
    if (questionnaire) {
      doc.text(`Questionnaire Questions: ${questionnaire.answers?.length || 0}`, 20, 100);
    }
    
    // Add footer
    doc.setFontSize(10);
    doc.setTextColor(128, 128, 128);
    doc.text('Generated by DentEdTech GDC Analyzer', pageWidth / 2, doc.internal.pageSize.height - 10, { align: 'center' });
    
    // Save the PDF
    doc.save(`GDC-${type}-${fileName}.pdf`);
    
    console.log(`✅ PDF generated: GDC-${type}-${fileName}.pdf`);
  }
}
